Updates SwitchOverview and NDT:EarlyWarning dashboards to use DISCOv2 data
m-lab/prometheus-support pull request #746
Opened 2020-09-23 22:42 UTC by nkinkade

Now that DISCOv2 is in production we can start making arrangements to retire snmp_exporter. Before doing that, however, we need to modify any dashboards that are currently using metrics from the snmp_exporter. This PR migrates two dashboards to use DISCOv2 metrics.

For the NDT:EarlyWarning dashboard all that was required was to migrate all the custom recording rules from the prometheus-federation cluster and to change the dashboard's datasources to Platform Cluster ones.

For Ops:SwitchOverview the principle change is adding a `machine=~"mlab2.*"` modifier to all queries. The use of mlab2 is arbitrary, as uplink metrics are collected by all 4 machines at a site. The datasources were also changed from prometheus-federation to Platform Cluster. Two panels were outright removed because they dealt with snmp_exporter scrape times, and pretty soon the snmp_exporter will no longer exist in our clusters.

2020-09-24 23:48 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/746)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[config/federation/grafana/dashboards/Ops_SwitchOverview.json, line 73 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/746#-MI1BM8a4v55A98EFgN6:-MI1BM8a4v55A98EFgN7:b-49p7y4) ([raw file](https://github.com/m-lab/prometheus-support/blob/7ae45332f57cfa44fa506c28ea34c22502195a28/config/federation/grafana/dashboards/Ops_SwitchOverview.json#L73)):*
> ```JSON
>         },
>         {
>           "expr": "max by (site) (quantile(0.90, 8 * irate(ifHCOutOctets{ifAlias=\"uplink\"}[4m])))",
> ```

Can you use `switch:ifHCOutOctets:bps2m` here?

Actually, I think that  the `max` belongs within the `quantile` everywhere so it's a quantile over sites rather than nodes at sites?


<!-- Sent from Reviewable.io -->

2020-09-25 20:09 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/746)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[config/federation/grafana/dashboards/Ops_SwitchOverview.json, line 73 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/746#-MI1BM8a4v55A98EFgN6:-MI5rq270re76TccxTcq:bf1wz9) ([raw file](https://github.com/m-lab/prometheus-support/blob/7ae45332f57cfa44fa506c28ea34c22502195a28/config/federation/grafana/dashboards/Ops_SwitchOverview.json#L73)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Can you use `switch:ifHCOutOctets:bps2m` here?

Actually, I think that  the `max` belongs within the `quantile` everywhere so it's a quantile over sites rather than nodes at sites?
</blockquote></details>

Good catch on moving `max()` inside of `quantile()`. Done.

Regarding the recording rule, would using it give us a better representation? If not, them I'm inclined to continue using regular metrics for the sake of clarity. It would also seam awkward to have `ifHCOutOctets` represented by a recording rule while `ifHCInOctets` remained a regular metric. If we went with the recording rule, then I'd want to create another one for `ifHCInOctets`.

I also realized the max and min queries on the first panel were incorrect. In those cases we don't want max-by-site, but simply calling `max()` and `min()` will give us what we want.


<!-- Sent from Reviewable.io -->

2020-09-25 20:22 UTC, stephen-soltesz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/746#-:-MI5vdGl5DQHs_puEMZg:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2020-09-25 23:39 UTC, stephen-soltesz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> :+1:

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/746#-:-MI6cisY3KX5JedoU3uE:bb67zex)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2020-09-28 16:18 UTC, merged