Adds new alert for when IPv6 is down for too long
m-lab/prometheus-support pull request #836
Opened 2021-08-04 21:42 UTC by nkinkade

This commit should resolve the case where IPv6 is down for one or all machines at a site without anyone knowing about it.

2021-08-04 21:47 UTC, stephen-soltesz commented
@cristinaleonr would you take a look at this also? What questions do you have?

@nkinkade I'll take a look tomorrow.

2021-08-04 22:05 UTC, nkinkade commented
@cristinaleonr: If you'd like to take stab at reviewing this, let me know and I'd be happy to walk you through what the query is doing, because it contains patterns that are very useful and that we use often, notwithstanding the abusive use of `label_replace()`.

2021-08-05 13:10 UTC, cristinaleonr reviewed
@nkinkade happy to chat with you about it, thanks! Let me know when you have some time.

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/836#-:-MgLQgMK6c-ImL37drvu:b-mzhmpu)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)



<!-- Sent from Reviewable.io -->

2021-08-05 19:53 UTC, cristinaleonr approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/836#-:-MgMsG834IqYteZ92whS:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)



<!-- Sent from Reviewable.io -->

2021-08-05 21:08 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/836)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN6isk2NPHREdatH3y:-MgN6isk2NPHREdatH3z:b92lcek) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/-- commits#L1)):*
Is this new behavior from reviewable? 
___
*[config/federation/prometheus/alerts.yml, line 501 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN75XH3yo0GvKPgRdN:-MgN75XH3yo0GvKPgRdO:b9rawfp) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L501)):*
> ```YAML
>       count by (site) (
>         label_replace(
>           probe_success{service="ndt7_ipv6"} == 0
> ```

Do you recall why we never added a `site=` label to `mlabconfig.py` output?
___
*[config/federation/prometheus/alerts.yml, line 507 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN7PnHEptLhl9-YVLT:-MgN7PnHEptLhl9-YVLU:bgd7q8u) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L507)):*
> ```YAML
>       )
>       unless on(site)
>         probe_success{module="icmp", instance=~"s1.(del02|los02|tnr01).*"}
> ```

does mlabconfig genenrate ipv6 records for sites where the ipv6 config is null? If so, is that necessary / or, what would be the downstream consequence if it didn't? I'm asking b/c this may not be the complete set in time. Better if the metric above never existed.
___
*[config/federation/prometheus/alerts.yml, line 511 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN7qXqD4UBd_k2tRe8:-MgN7qXqD4UBd_k2tRe9:b-q1m6fq) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L511)):*
> ```YAML
>         label_replace(
>           gmx_machine_maintenance == 1,
>           "site", "$1", "machine", "mlab[1-4].([a-z]{3}[0-9]{2}).*"
> ```

is the site label necessary here and below since this block is matching `on(machine)` ?


<!-- Sent from Reviewable.io -->

2021-08-05 21:32 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/836)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @stephen-soltesz)

*[a discussion](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgNDkv40TcRpHRptZ3N:-MgNDkv40TcRpHRptZ3O:b-rp8kfl) (no related file):*
@stephen-soltesz: Comments added.

---
___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN6isk2NPHREdatH3y:-MgN9r6U3ao8nQ3Grg1e:b-i9cxbx) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/-- commits#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this new behavior from reviewable? 
</blockquote></details>

I don't think I've ever seen a "Commits" tab like this before. It may be new.
___
*[config/federation/prometheus/alerts.yml, line 501 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN75XH3yo0GvKPgRdN:-MgN9y6K4KgduDsuHOGx:bbi3cej) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L501)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do you recall why we never added a `site=` label to `mlabconfig.py` output?
</blockquote></details>

I don't, but after I wrote this PR, I decided that I was going to look into adding a `site` label to every single metric that Prometheus scrapes from the platform cluster that has a `node` label. In fact, I think I could do that, and then rework this PR. What do you think?
___
*[config/federation/prometheus/alerts.yml, line 507 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN7PnHEptLhl9-YVLT:-MgNBVPP5T9mvkdgiWo3:b-w7qm49) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L507)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

does mlabconfig genenrate ipv6 records for sites where the ipv6 config is null? If so, is that necessary / or, what would be the downstream consequence if it didn't? I'm asking b/c this may not be the complete set in time. Better if the metric above never existed.
</blockquote></details>

Yeah, mlabconfig.py generates BBE targets for every site, regardless of whether it actually has IPv6. In my mind, the current behavior is probably correct. I think we want to have a `probe_success` metric for _every_ machine. That is, allowing BBE to probe IPv6 services at sites we know have no IPv6 connectivity gives us a definitive metric for machine/service saying that it is down. If the metric did not exist, then it is likely that the [mlab-ns query](https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/util/prometheus_status.py#L98) for, say `ndt7_ipv6` might return a `1` (up) value, as long as all the other metrics were healthy, because the `probe_success{service="ndt7_ipv6"}` would not even exist.
___
*[config/federation/prometheus/alerts.yml, line 511 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN7qXqD4UBd_k2tRe8:-MgNCi-JCAG6bde_iwdi:bv4o11b) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L511)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

is the site label necessary here and below since this block is matching `on(machine)` ?
</blockquote></details>

It is in the current configuration of the query. The top part of the query does a `count by (site) ()`, the result of which only contains a `site` label and nothing more. The rationale behind doing this is that in almost every scenario I can think, IPv6 will either work for the whole site, or will be down for the entire site. Doing the grouping like this allows a single alert to fire if 1 to all of the machines at a site are failing. This is useful for the, very unlikely, event that IPv6 is down for only a single node. Without the grouping by site, if IPv6 went down for the entire site, then we would get 4 alerts, one for each machine.


<!-- Sent from Reviewable.io -->

2021-08-05 22:58 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/836)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[config/federation/prometheus/alerts.yml, line 501 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN75XH3yo0GvKPgRdN:-MgNUtq-E1z9vvUy5RlN:b-3ab4jm) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L501)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I don't, but after I wrote this PR, I decided that I was going to look into adding a `site` label to every single metric that Prometheus scrapes from the platform cluster that has a `node` label. In fact, I think I could do that, and then rework this PR. What do you think?
</blockquote></details>

I like it :+1: 
___
*[config/federation/prometheus/alerts.yml, line 507 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN7PnHEptLhl9-YVLT:-MgNV6n4BrDwWsxMEK0W:bs12iuu) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L507)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Yeah, mlabconfig.py generates BBE targets for every site, regardless of whether it actually has IPv6. In my mind, the current behavior is probably correct. I think we want to have a `probe_success` metric for _every_ machine. That is, allowing BBE to probe IPv6 services at sites we know have no IPv6 connectivity gives us a definitive metric for machine/service saying that it is down. If the metric did not exist, then it is likely that the [mlab-ns query](https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/util/prometheus_status.py#L98) for, say `ndt7_ipv6` might return a `1` (up) value, as long as all the other metrics were healthy, because the `probe_success{service="ndt7_ipv6"}` would not even exist.
</blockquote></details>

Hmm... is there another way to eliminate the explicit site list? a new label perhaps? `ipv6="provided"/"missing"? (or similar) -- the explicit site list will not age well. Could be okay with a TODO for now, but I hope we can make it automatic.
___
*[config/federation/prometheus/alerts.yml, line 511 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN7qXqD4UBd_k2tRe8:-MgNXWCZ8qJpxODWBsxG:bvm08rf) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L511)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

It is in the current configuration of the query. The top part of the query does a `count by (site) ()`, the result of which only contains a `site` label and nothing more. The rationale behind doing this is that in almost every scenario I can think, IPv6 will either work for the whole site, or will be down for the entire site. Doing the grouping like this allows a single alert to fire if 1 to all of the machines at a site are failing. This is useful for the, very unlikely, event that IPv6 is down for only a single node. Without the grouping by site, if IPv6 went down for the entire site, then we would get 4 alerts, one for each machine.
</blockquote></details>

Something doesn't feel right. Let me look at the query more closely.


<!-- Sent from Reviewable.io -->

2021-08-05 23:09 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/836)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[config/federation/prometheus/alerts.yml, line 511 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN7qXqD4UBd_k2tRe8:-MgNYwYV52cjnJ4fpl4J:b-ic8lvj) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L511)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Something doesn't feel right. Let me look at the query more closely.
</blockquote></details>

Run the first part of the query in prometheus:

```
      count by (site) (
        label_replace(
          probe_success{service="ndt7_ipv6"} == 0
            unless on(machine) probe_success{service="ndt7"} == 0,
          "site", "$1", "machine", "mlab[1-4].([a-z]{3}[0-9]{2}).*"
        )
      )
```

This block returns time series with only the "site" label.

The remaining `unless on(machine)` are effectively no-ops. There is no `machine` label in the opening query to match on the remaining set returned by the query within `unless`.

For example, this (on a meaningless label) returns the same set as the above.

```
      count by (site) (
        label_replace(
          probe_success{service="ndt7_ipv6"} == 0
            unless on(machine) probe_success{service="ndt7"} == 0,
          "site", "$1", "machine", "mlab[1-4].([a-z]{3}[0-9]{2}).*"
        )
      )
      unless on(instance) (
        label_replace(gmx_machine_maintenance == 1, "site", "$1", "machine", "mlab[1-4].([a-z]{3}[0-9]{2}).*")
      )
```

Think of PromQL queries as set operations.

PTAL?


<!-- Sent from Reviewable.io -->

2021-08-05 23:15 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/836)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[config/federation/prometheus/alerts.yml, line 511 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN7qXqD4UBd_k2tRe8:-MgNaBayA_siW98giC3N:biibvll) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L511)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Run the first part of the query in prometheus:

```
      count by (site) (
        label_replace(
          probe_success{service="ndt7_ipv6"} == 0
            unless on(machine) probe_success{service="ndt7"} == 0,
          "site", "$1", "machine", "mlab[1-4].([a-z]{3}[0-9]{2}).*"
        )
      )
```

This block returns time series with only the "site" label.

The remaining `unless on(machine)` are effectively no-ops. There is no `machine` label in the opening query to match on the remaining set returned by the query within `unless`.

For example, this (on a meaningless label) returns the same set as the above.

```
      count by (site) (
        label_replace(
          probe_success{service="ndt7_ipv6"} == 0
            unless on(machine) probe_success{service="ndt7"} == 0,
          "site", "$1", "machine", "mlab[1-4].([a-z]{3}[0-9]{2}).*"
        )
      )
      unless on(instance) (
        label_replace(gmx_machine_maintenance == 1, "site", "$1", "machine", "mlab[1-4].([a-z]{3}[0-9]{2}).*")
      )
```

Think of PromQL queries as set operations.

PTAL?
</blockquote></details>

Not for this PR but in general: prometheus supports unit tests for alerts - our use of this feature may be over due -- https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/


<!-- Sent from Reviewable.io -->

2021-08-06 15:11 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/836)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[config/federation/prometheus/alerts.yml, line 511 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN7qXqD4UBd_k2tRe8:-MgR-xIn-Zdh2-aNCFaU:blp15om) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L511)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Not for this PR but in general: prometheus supports unit tests for alerts - our use of this feature may be over due -- https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/
</blockquote></details>

You found a bug in the query. Thanks! My reply to your original comment basically lays out the same thing you explain in detail above. That is, I don't think my understanding of PromQL was off, but I just had a bug in the query.


<!-- Sent from Reviewable.io -->

2021-08-10 17:06 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/836)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @stephen-soltesz)

*[a discussion](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgNDkv40TcRpHRptZ3N:-Mgl0FXRBk1ha5pvhW-z:bsm43vs) (no related file):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

@stephen-soltesz: Comments added.
</blockquote></details>

@stephen-soltesz: I have reworked various things in the PR. PTAL?

I'll acknowledge here, that various changes in this PR now have interdependencies. That is, the changes are not fully tested. For example, the query makes use of a new `ipv6` label in BBE probes, yet that label does not exist in staging yet, and won't exist there until this PR is merged.

---
___
*[config/federation/prometheus/alerts.yml, line 501 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN75XH3yo0GvKPgRdN:-Mgl-4ky60tkp8_b8Z8t:b-rms3b5) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L501)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I like it :+1: 
</blockquote></details>

I have added new `site` labels to pretty much any metric that originates from the platform cluster in some way. I had also added a `site` label to GMX machine maintenance metrics.
___
*[config/federation/prometheus/alerts.yml, line 507 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN7PnHEptLhl9-YVLT:-Mgl-LdbExxOWxrJcwD-:b-5k4scc) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L507)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm... is there another way to eliminate the explicit site list? a new label perhaps? `ipv6="provided"/"missing"? (or similar) -- the explicit site list will not age well. Could be okay with a TODO for now, but I hope we can make it automatic.
</blockquote></details>

 I added a new `ipv6` label to all blackbox_exporter metrics. The possible values are `ipv6="present"` and `ipv6="missing"`.  We can now filter out sites where an IPv6 address is missing for an experiment, which only happens when the entire site doesn't support IPv6.
___
*[config/federation/prometheus/alerts.yml, line 511 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN7qXqD4UBd_k2tRe8:-Mgl-acD7y3vAyN37u2B:b-vus9em) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L511)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

You found a bug in the query. Thanks! My reply to your original comment basically lays out the same thing you explain in detail above. That is, I don't think my understanding of PromQL was off, but I just had a bug in the query.
</blockquote></details>

After all the time spent adding a new `site` label to a lot of metrics, I have reworked this query to not even need it in as many places. The query now does all matching on `machine`, and _then_, after all filtering is done, it groups by site. The way I had written the query before, filtering on `site` for `gmx_machine_maintenance` and `kube_node_spec_taint` could have possibly masked an IPv6 issue on a single node, since one machine could have an IPv6 issue, and another at a site could be in GMX mode, yet the GMX'ed machine would have matches the IPv6-issue-node on "site", and thereby masked it.


<!-- Sent from Reviewable.io -->

2021-08-10 19:35 UTC, stephen-soltesz approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/836)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @nkinkade)

*[a discussion](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgNDkv40TcRpHRptZ3N:-MglYuwAAM6iJShrQ_eg:b-vl3jox) (no related file):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

@stephen-soltesz: I have reworked various things in the PR. PTAL?

I'll acknowledge here, that various changes in this PR now have interdependencies. That is, the changes are not fully tested. For example, the query makes use of a new `ipv6` label in BBE probes, yet that label does not exist in staging yet, and won't exist there until this PR is merged.
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> -- thank you! The final query is much much simpler!

---
___
*[config/federation/prometheus/alerts.yml, line 501 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN75XH3yo0GvKPgRdN:-MglPb6ADmQeTprMdiSN:b-wsl22e) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L501)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I have added new `site` labels to pretty much any metric that originates from the platform cluster in some way. I had also added a `site` label to GMX machine maintenance metrics.
</blockquote></details>

Awesome! Thank you for taking the extra steps. I think this overall effort is a superb example of the heuristic I have that there's at least a 10:1 exchange rate for Go code to PromQL -- simpler PromQL queries are worth it. Thank you.
___
*[config/federation/prometheus/alerts.yml, line 507 at r1](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MgN7PnHEptLhl9-YVLT:-MglPyd5C8PSq9k86bUf:b-ec019s) ([raw file](https://github.com/m-lab/prometheus-support/blob/aac22c776c43b8549cac2463243e33d3dbbfbcea/config/federation/prometheus/alerts.yml#L507)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

 I added a new `ipv6` label to all blackbox_exporter metrics. The possible values are `ipv6="present"` and `ipv6="missing"`.  We can now filter out sites where an IPv6 address is missing for an experiment, which only happens when the entire site doesn't support IPv6.
</blockquote></details>

Excellent!
___
*[config/federation/prometheus/alerts.yml, line 496 at r2](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MglYj9B8DPPCRvl1_3G:-MglYj9B8DPPCRvl1_3H:bpxfayd) ([raw file](https://github.com/m-lab/prometheus-support/blob/78ab2b9dcb3f5c1dc32384ea7fa7386b233e9f48/config/federation/prometheus/alerts.yml#L496)):*
> ```YAML
>         probe_success{service="ndt7_ipv6", ipv6="present"} == 0
>           unless on(machine) probe_success{service="ndt7"} == 0
>         unless on(machine) (
> ```

nit: there is no standard convention for promql formatting. I'd recommend putting the `unless` clauses at the same indent level.

```
      count by (site) (
        probe_success{service="ndt7_ipv6", ipv6="present"} == 0
          unless on(machine) probe_success{service="ndt7"} == 0
          unless on(machine) (
            gmx_machine_maintenance == 1 or
            kube_node_spec_taint{cluster="platform", key="lame-duck"}
          )
      ) > 0
```


<!-- Sent from Reviewable.io -->

2021-08-10 19:45 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/prometheus-support/836)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @nkinkade)

___
*[config/federation/prometheus/alerts.yml, line 496 at r2](https://reviewable.io/reviews/m-lab/prometheus-support/836#-MglYj9B8DPPCRvl1_3G:-Mgl_hqI154IKdYEg1Vo:bw1mue0) ([raw file](https://github.com/m-lab/prometheus-support/blob/78ab2b9dcb3f5c1dc32384ea7fa7386b233e9f48/config/federation/prometheus/alerts.yml#L496)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: there is no standard convention for promql formatting. I'd recommend putting the `unless` clauses at the same indent level.

```
      count by (site) (
        probe_success{service="ndt7_ipv6", ipv6="present"} == 0
          unless on(machine) probe_success{service="ndt7"} == 0
          unless on(machine) (
            gmx_machine_maintenance == 1 or
            kube_node_spec_taint{cluster="platform", key="lame-duck"}
          )
      ) > 0
```
</blockquote></details>

Done. That said, the indention I had was intentional. Right or wrong, I viewed the first `unless` clause as a more tightly coupled part of the `probe_success` query, like a compound statement. Then, the second `unless` was filtering things on a different category. In any case, it's all indented at the same level now.


<!-- Sent from Reviewable.io -->

2021-08-10 20:04 UTC, merged